### ISSUE TITLE
Feature Request/Bug: Player Changed after wake up, timing issue

### ISSUE THREAD

**Issue by poggenpower** [nikclayton/android-squeezer#181] opened 2016-11-24 11:23 UTC
Hi,

I have several hardware (Boom, Radio) and software players (SqueezePlayer Android). I most cases I use Squeezer to control SqueezePlayer on the same device.
But if the android device went to sleep and I use Squeezer again a hardware player (depending which one is first in the list) is selected. 
This seems to be a timing issue, because the local SqueezePlayer needs to register to the LMS after wake up and the hardware player are already connected and listed on LMS. So the local SqueezPlayer is not in the list of players Squeezer has received at wake up. But appears a few seconds later.
On the one hand, it could be useful and comfortable, because Squeezer switches to an available player.
On the other hand, it is very confusing, because you expect to control the same player you used the last time, but you may start something in a complete different room without notification(very unpleasant if you wake up you child by this mistake)  
There are several options how to handle this.
Option1: Don't switch to an other player automatically, display an error and show a list of players available. Recover automatically if the former selected player appears. 
Option2: optional setting: Connect to preferred player $NAME if available.
Option3: at least show an message, that Squeezer has selected a new player $NAME, than the user is aware of.

No idea how hard this is to fix. In any case I would like to say thank you for sending all the time in developing this great app. I like it very much. Would like to see something similar on IOS. Great work! Thanks!

Bye
 Thomas

**Comment by kaaholst** [comment] 2016-11-27 22:13
Thanks for the report, and you detailed description.

I think you are right in that it is a timing issue. Squeezer receives the list of players from LMS before SqueezePlayer registers with LMS. When Squeezer connects to LMS it attempt to reuse the active player from the previous session. If this player is not available it will use the first on the list.

I don't think there's an easy fix for this, but your options are certainly welcomed.

**Comment by kaaholst** [comment] 2021-01-22 07:36
This issue is a duplicate of #109 you can follow the progress there. So closing this.

**Closed by kaaholst** 2021-01-22 07:36 UTC
