### ISSUE TITLE
Automatic connection on app startup

### ISSUE THREAD

**Issue by beejayf** [nikclayton/android-squeezer#639] opened 2020-05-16 09:11 UTC
Hi all!
Thanks so much for creating squeeze, I love it and I use it a lot! 

There is just a small issue: if I open the app it almost asks me each time what server I want to connect to. I confirm the preselected (only) server and it connects. 

I only have one server in my network, I don't use my squeezebox.com and left it blank in the settings. 

Is this a small bug or is there a workaround so that the app won't ask on startup?

Thanks and keep up the excellent work!

BeeJayF

**Comment by eremem** [comment] 2020-05-18 10:20
I observe the same behavior. I suppose it can be due to the energy saving policy, where either the application or the WiFi connection is being put into sleep. Still it would be nice if squeezer connected to the latest selected server automatically in this case as it does while being manually started.

**Comment by diyfiddler** [comment] 2020-07-17 07:00
Hi,  Yes I'd also agree with this.  On android 10 (Xiaomi Mi A2 Lite), I'm often, but not always, presented with the connection screen on app start or restart, which just requires the hitting the 'CONNECT' button as all the other settings are good to go.  I'm not sure if the 1st attempt at automatic connection times out or something, but perhaps the app could try more than once to connect automatically?,

**Comment by dbu828** [comment] 2020-07-25 09:39
Same here in Android V10.

**Comment by kaaholst** [comment] 2020-09-17 21:39
Version 2.2.0 connects automatically unless it's disconnected manually (via the disconnect from the 3-dot options menu in the top right corner).
I thinks some of the disconnects is caused by Android closing either network or the Squeezer service, depending on Android version and device model, so I'm afraid I can't do anything about that.
Thanks for the feedback

**Closed by kaaholst** 2020-09-17 21:39 UTC
