### ISSUE TITLE
Download non-functional (Motorola g(7) Play; Android 9; squeezer 1.5.2)

### ISSUE THREAD

**Issue by csrhodes** [nikclayton/android-squeezer#514] opened 2019-09-17 07:32 UTC
Hi,

The download operation in Squeezer has stopped working on my phone.  It used to work on this phone (and on previous phones); I think it stopped working *before* the automatic upgrade to squeezer 1.5.2, but I am not sure.

I have verified that I can manually download files from LMS from the phone, using the test process in #143 - the download completes fine.  I have also checked using tcpdump on the LMS machine, and it does not seem to receive any request for the file from squeezer.

I'm happy to try to debug this situation more, if there are other ideas for how to help diagnose the problem.

Thank you,

Christophe

**Comment by kaaholst** [comment] 2019-09-17 21:12
I had a similar issue.

Squeezer doesn't download files directly, instead we download them through he Android download manager, which queues up the download requests, downloads the files when network is available, and notifies Squeezer when a download is complete. 

Maybe the problem is located in the download manager, here is an article on how to fix it (look for issue 9. Downloads Not Working):
[20 Common Android Problems Solved](https://www.makeuseof.com/tag/20-common-android-problems-solved/)

**Comment by csrhodes** [comment] 2019-09-17 21:39
Thank you.  I tried clearing cache, removing all data, force stopping the download manager and rebooting, but unfortunately I'm still in the same state: issuing the download action appears to do nothing.  Thanks for the idea, though

**Comment by kaaholst** [comment] 2020-09-17 21:43
The new download implementation in 2.2.0 throttles the downloads so we won't have issues with Android rate limiting the requests to the download manager.
This problem should be solved now, so closing this.
If you still have a problem, please reopen or create a new issue.

**Closed by kaaholst** 2020-09-17 21:43 UTC
