### ISSUE TITLE
Feature request: Favourite music item.

### ISSUE THREAD

**Issue by vigliensoni** [nikclayton/android-squeezer#172] opened 2016-06-30 01:11 UTC
Similarly to the web-based client and SqueezePad, it would very useful to being able to save the currently played music item (i.e., track, album, or artist) to SB's favourites.

Keep the great work!

**Comment by nikclayton** [comment] 2017-03-18 17:02
Duplicate of #37, closing, will track work there.

**Closed by nikclayton** 2017-03-18 17:02 UTC
